# Generated by Django 6.0.2 on 2026-09-20 15:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_product_purchase_price'),
        ('stock', '0003_stockmovement_sale_line_alter_stocklevel_quantity'),
        ('tenants', '0010_boutique_delivery_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=40)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='date de réception')),
                ('reference', models.CharField(blank=True, help_text='N° de la facture ou du bon de livraison du fournisseur.', max_length=100, verbose_name='référence fournisseur')),
                ('note', models.TextField(blank=True)),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.boutique')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'réception de marchandises',
                'verbose_name_plural': 'réceptions de marchandises',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='coût unitaire')),
                ('line_total', models.DecimalField(decimal_places=0, max_digits=14)),
                ('cost_before', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('cost_after', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_line', to='stock.stockmovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='catalog.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchase')),
            ],
            options={
                'verbose_name': 'ligne de réception',
                'verbose_name_plural': 'lignes de réception',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.compte')),
            ],
            options={
                'verbose_name': 'fournisseur',
                'verbose_name_plural': 'fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='purchasing.supplier'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('compte', 'name'), name='unique_supplier_name_par_compte'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('boutique', 'number'), name='unique_purchase_number_par_boutique'),
        ),
    ]
