# Generated by Django 6.0.2 on 2026-09-20 18:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_alter_personalcashmovement_kind'),
        ('purchasing', '0001_initial'),
        ('tenants', '0010_boutique_delivery_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('LOYER', 'Loyer'), ('SALAIRES', 'Salaires'), ('TRANSPORT', 'Transport'), ('ENERGIE', 'Électricité, eau, internet'), ('MARKETING', 'Publicité, marketing'), ('ENTRETIEN', 'Entretien, réparations'), ('TAXES', 'Taxes et impôts'), ('AUTRE', 'Autre')], max_length=20, verbose_name='catégorie')),
                ('label', models.CharField(max_length=255, verbose_name='libellé')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='montant')),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='date')),
                ('note', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.boutique')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cash_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='cashier.personalcashmovement')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dépense',
                'verbose_name_plural': 'dépenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
