# Generated by Django 6.0.7 on 2026-07-31 15:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF / identifiant fiscal')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.boutique')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('DEVIS', 'Devis'), ('FACTURE', 'Facture')], default='FACTURE', max_length=10)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('PAYEE', 'Payée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('ANNULEE', 'Annulée'), ('CONVERTIE', 'Convertie en facture')], default='BROUILLON', max_length=25)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('subtotal_ht', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('total_tva', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.boutique')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.client')),
                ('converted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='sales.invoice')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'facture / devis',
                'verbose_name_plural': 'factures / devis',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price_ht', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tva_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total_ht', models.DecimalField(decimal_places=0, max_digits=14)),
                ('line_total_ttc', models.DecimalField(decimal_places=0, max_digits=14)),
                ('position', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='catalog.product')),
            ],
            options={
                'verbose_name': 'ligne de facture',
                'verbose_name_plural': 'lignes de facture',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('method', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement'), ('CARTE', 'Carte'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.boutique')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.invoice')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='taux (%)')),
                ('is_default', models.BooleanField(default=False)),
                ('active_from', models.DateField(default=django.utils.timezone.localdate)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.compte')),
            ],
            options={
                'verbose_name': 'taux de TVA',
                'verbose_name_plural': 'taux de TVA',
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('boutique', 'number'), name='unique_invoice_number_par_boutique'),
        ),
    ]
