# Generated by Django 6.0.7 on 2026-08-01 03:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('sale_date', models.DateField(default=django.utils.timezone.localdate)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('subtotal_ht', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('total_tva', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.boutique')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='sales.invoice')),
            ],
            options={
                'verbose_name': 'vente',
                'verbose_name_plural': 'ventes',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price_ht', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tva_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total_ht', models.DecimalField(decimal_places=0, max_digits=14)),
                ('line_total_ttc', models.DecimalField(decimal_places=0, max_digits=14)),
                ('position', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='catalog.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale')),
            ],
            options={
                'verbose_name': 'ligne de vente',
                'verbose_name_plural': 'lignes de vente',
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('boutique', 'number'), name='unique_sale_number_par_boutique'),
        ),
    ]
