# Generated by Django 6.0.7 on 2026-08-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_saleline_sale_unique_sale_number_par_boutique'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='remise globale (%)'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='remise (%)'),
        ),
    ]
