# Generated by Django 6.0.7 on 2026-08-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_discount_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='remise globale (FCFA)'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='remise (FCFA)'),
        ),
    ]
