# Generated by Django 6.0.7 on 2026-08-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_invoice_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('DEVIS', 'Devis'), ('FACTURE', 'Facture'), ('COMMANDE', 'Commande')], default='FACTURE', max_length=10),
        ),
    ]
