# Generated by Django 6.0.7 on 2026-08-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='note',
            field=models.TextField(blank=True, help_text="Usage interne uniquement — n'apparaît jamais sur le reçu/PDF.", verbose_name='note interne'),
        ),
    ]
