# Generated by Django 6.0.7 on 2026-08-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_invoice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_format',
            field=models.CharField(choices=[('80MM', 'Ticket 80mm'), ('A4', 'A4')], default='80MM', max_length=10, verbose_name='format du PDF'),
        ),
    ]
