# Generated by Django 6.0.2 on 2026-09-15 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_invoice_pdf_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='livrée le'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_livrees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée')], default='EN_ATTENTE', max_length=15, verbose_name='statut de livraison'),
        ),
    ]
