# Generated by Django 6.0.2 on 2026-09-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_invoice_delivered_at_invoice_delivered_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
