# Generated by Django 6.0.2 on 2026-09-20 18:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_saleline_unit_cost'),
        ('tenants', '0010_boutique_delivery_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('channel', models.CharField(choices=[('API', "Envoyée par l'API WhatsApp"), ('LINK', 'Ouverte dans WhatsApp')], max_length=10)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.boutique')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='sales.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='sales.invoice')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'relance de paiement',
                'verbose_name_plural': 'relances de paiement',
                'ordering': ['-created_at'],
            },
        ),
    ]
