# Generated by Django 6.0.2 on 2026-09-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_invoice_commande_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('EN_MAGASIN', 'En magasin'), ('LIVREE', 'Livrée')], default='EN_ATTENTE', max_length=15, verbose_name='statut de livraison'),
        ),
    ]
