# Generated by Django 6.0.7 on 2026-08-10 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_invoice_discount_percent_and_more'),
        ('stock', '0002_stockmovement_reference_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='sale_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.saleline'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
