# Generated by Django 6.0.7 on 2026-07-31 15:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='nom de la boutique')),
                ('code', models.CharField(help_text='Préfixe utilisé pour numéroter les factures hors-ligne (ex: BTQ-001).', max_length=10, verbose_name='code court')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Boutique sélectionnée automatiquement à la connexion pour cette entreprise.', verbose_name='boutique par défaut')),
            ],
            options={
                'verbose_name': 'boutique',
                'verbose_name_plural': 'boutiques',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name="nom de l'entreprise")),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('plan', models.CharField(choices=[('GRATUIT', 'Gratuit'), ('STANDARD', 'Standard')], default='GRATUIT', max_length=20)),
            ],
            options={
                'verbose_name': 'entreprise',
                'verbose_name_plural': 'entreprises',
            },
        ),
        migrations.CreateModel(
            name='BoutiqueAPIToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('boutique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to='tenants.boutique')),
            ],
            options={
                'verbose_name': 'jeton API boutique',
                'verbose_name_plural': 'jetons API boutique',
            },
        ),
        migrations.AddField(
            model_name='boutique',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutiques', to='tenants.compte'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('ADMIN_COMPTE', "Administrateur de l'entreprise"), ('GERANT_BOUTIQUE', 'Gérant de boutique'), ('CAISSIER', 'Caissier')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.boutique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'affectation',
                'verbose_name_plural': 'affectations',
            },
        ),
        migrations.AddConstraint(
            model_name='boutique',
            constraint=models.UniqueConstraint(fields=('compte', 'code'), name='unique_boutique_code_par_compte'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'boutique'), name='unique_membership_user_boutique'),
        ),
    ]
