# Generated by Django 6.0.7 on 2026-08-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='logo',
            field=models.ImageField(blank=True, help_text='Affiché en haut des factures/devis (ticket 80 mm).', null=True, upload_to='logos/', verbose_name="logo de l'entreprise"),
        ),
    ]
