# Generated by Django 6.0.7 on 2026-08-04 08:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_compte_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('price_monthly', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='prix mensuel (FCFA)')),
                ('max_boutiques', models.PositiveIntegerField(blank=True, help_text='Laisser vide = illimité', null=True, verbose_name='nombre de boutiques max')),
                ('max_users', models.PositiveIntegerField(blank=True, help_text='Laisser vide = illimité', null=True, verbose_name="nombre d'employés max")),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='proposé aux entreprises')),
            ],
            options={
                'verbose_name': "offre d'abonnement",
                'verbose_name_plural': "offres d'abonnement",
                'ordering': ['price_monthly'],
            },
        ),
        migrations.RemoveField(
            model_name='compte',
            name='plan',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='débuté le')),
                ('expires_at', models.DateField(blank=True, help_text='Laisser vide pour une offre sans limite de durée (ex: plan gratuit).', null=True, verbose_name='expire le')),
                ('payment_reference', models.CharField(blank=True, help_text='Ex: référence Mobile Money, numéro de virement...', max_length=255, verbose_name='référence de paiement')),
                ('notes', models.TextField(blank=True)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.compte')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.plan')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
            },
        ),
    ]
