# Generated by Django 6.0.7 on 2026-08-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_seed_default_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='country_calling_code',
            field=models.CharField(blank=True, help_text='Complète automatiquement les numéros WhatsApp saisis sans indicatif (ex: 07... devient +225 07...).', max_length=4, verbose_name='indicatif téléphonique du pays'),
        ),
    ]
