# Generated by Django 6.0.7 on 2026-08-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_boutique_country_calling_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='momo_account_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='MTN MoMo — nom du compte'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='momo_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='MTN MoMo — numéro'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='om_account_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Orange Money — nom du compte'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='om_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Orange Money — numéro'),
        ),
    ]
