# Generated by Django 6.0.7 on 2026-08-08 19:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_boutique_momo_account_name_boutique_momo_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3, verbose_name='devise')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Valeur de 1 unité de cette devise, exprimée dans la devise de la boutique. Ex: 1 EUR = 655.9570 XOF.', max_digits=14, verbose_name='taux')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='tenants.boutique')),
            ],
            options={
                'verbose_name': 'taux de change',
                'verbose_name_plural': 'taux de change',
                'ordering': ['currency'],
                'constraints': [models.UniqueConstraint(fields=('boutique', 'currency'), name='unique_exchange_rate_par_devise')],
            },
        ),
    ]
