# Generated by Django 6.0.7 on 2026-08-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiqueapitoken',
            name='last_pull_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boutiqueapitoken',
            name='last_push_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
