# Generated by Django 6.0.7 on 2026-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_boutiqueapitoken_last_pull_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutiqueapitoken',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
