# Generated by Django 6.0.2 on 2026-09-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_boutiqueapitoken_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Déduit automatiquement de la caisse individuelle de la personne qui livre, à chaque commande marquée « Livrée ». Laisser vide pour ne rien déduire.', max_digits=14, null=True, verbose_name='prix de livraison'),
        ),
    ]
