# Generated by Django 6.0.7 on 2026-08-10 05:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0008_boutiqueapitoken_last_pull_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull')], default='PUSH', max_length=4)),
                ('endpoint', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('response_snapshot', models.JSONField()),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='tenants.boutique')),
            ],
            options={
                'verbose_name': 'journal de synchronisation',
                'verbose_name_plural': 'journaux de synchronisation',
                'indexes': [models.Index(fields=['boutique', 'created_at'], name='sync_synclo_boutiqu_f35e96_idx')],
                'constraints': [models.UniqueConstraint(fields=('boutique', 'endpoint', 'idempotency_key'), name='unique_synclog_key')],
            },
        ),
    ]
