# Generated by Django 6.0.7 on 2026-08-10 07:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_alter_synclog_response_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boutique_id', models.UUIDField()),
                ('boutique_name', models.CharField(max_length=255)),
                ('compte_id', models.UUIDField()),
                ('compte_name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'activation du poste',
                'verbose_name_plural': 'activation du poste',
            },
        ),
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('resource', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('client', 'Client'), ('stock_movement', 'Mouvement de stock'), ('invoice', 'Facture/devis'), ('payment', 'Paiement'), ('sale_transaction', 'Vente')], max_length=20)),
                ('object_id', models.UUIDField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('ERROR', 'Erreur')], default='PENDING', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'entrée de file de synchronisation',
                'verbose_name_plural': 'entrées de file de synchronisation',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'kind', 'created_at'], name='sync_outbox_status_bfb4f6_idx')],
            },
        ),
    ]
