# Generated by Django 6.0.7 on 2026-08-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_deviceactivation_synccursor_outboxentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxentry',
            name='kind',
            field=models.CharField(choices=[('client', 'Client'), ('stock_movement', 'Mouvement de stock'), ('invoice', 'Facture/devis'), ('payment', 'Paiement'), ('sale_transaction', 'Vente'), ('category', 'Catégorie'), ('unit', 'Unité'), ('product', 'Produit')], max_length=20),
        ),
    ]
