# Generated by Django 6.0.7 on 2026-08-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_alter_outboxentry_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceactivation',
            name='token_invalid',
            field=models.BooleanField(default=False),
        ),
    ]
