# Generated by Django 6.0.7 on 2026-08-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_deviceactivation_token_invalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxentry',
            name='kind',
            field=models.CharField(choices=[('client', 'Client'), ('stock_movement', 'Mouvement de stock'), ('invoice', 'Facture/devis'), ('payment', 'Paiement'), ('sale_transaction', 'Vente'), ('category', 'Catégorie'), ('unit', 'Unité'), ('product', 'Produit'), ('cash_session', 'Session de caisse'), ('cash_movement', 'Mouvement de caisse')], max_length=20),
        ),
    ]
