"""Devises proposées à la création d'une entreprise/boutique et pour une
vente/devis ponctuel dans une devise différente de celle par défaut de la
boutique — voir apps.tenants.models.Boutique.devise et
apps.sales.services.build_sale/build_invoice."""

CURRENCY_CHOICES = [
    ("XOF", "Franc CFA — UEMOA (XOF)"),
    ("XAF", "Franc CFA — CEMAC (XAF)"),
    ("NGN", "Naira nigérian (NGN)"),
    ("GHS", "Cedi ghanéen (GHS)"),
    ("KES", "Shilling kényan (KES)"),
    ("UGX", "Shilling ougandais (UGX)"),
    ("TZS", "Shilling tanzanien (TZS)"),
    ("RWF", "Franc rwandais (RWF)"),
    ("ZAR", "Rand sud-africain (ZAR)"),
    ("EGP", "Livre égyptienne (EGP)"),
    ("MAD", "Dirham marocain (MAD)"),
    ("DZD", "Dinar algérien (DZD)"),
    ("TND", "Dinar tunisien (TND)"),
    ("LYD", "Dinar libyen (LYD)"),
    ("CDF", "Franc congolais (CDF)"),
    ("GNF", "Franc guinéen (GNF)"),
    ("ETB", "Birr éthiopien (ETB)"),
    ("MZN", "Metical mozambicain (MZN)"),
    ("ZMW", "Kwacha zambien (ZMW)"),
    ("MWK", "Kwacha malawien (MWK)"),
    ("MGA", "Ariary malgache (MGA)"),
    ("BWP", "Pula botswanais (BWP)"),
    ("NAD", "Dollar namibien (NAD)"),
    ("LRD", "Dollar libérien (LRD)"),
    ("SLE", "Leone sierra-léonais (SLE)"),
    ("GMD", "Dalasi gambien (GMD)"),
    ("CVE", "Escudo cap-verdien (CVE)"),
    ("STN", "Dobra santoméen (STN)"),
    ("SCR", "Roupie seychelloise (SCR)"),
    ("MUR", "Roupie mauricienne (MUR)"),
    ("KMF", "Franc comorien (KMF)"),
    ("DJF", "Franc djiboutien (DJF)"),
    ("SOS", "Shilling somalien (SOS)"),
    ("SDG", "Livre soudanaise (SDG)"),
    ("SSP", "Livre sud-soudanaise (SSP)"),
    ("USD", "Dollar américain (USD)"),
    ("EUR", "Euro (EUR)"),
    ("GBP", "Livre sterling (GBP)"),
]
