# Generated by Django 6.0.7 on 2026-07-31 15:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.compte')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='symbole')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.compte')),
            ],
            options={
                'verbose_name': 'unité',
                'verbose_name_plural': 'unités',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=64, verbose_name='référence (SKU)')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='code-barres')),
                ('default_sale_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='prix de vente (FCFA)')),
                ('tva_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='taux de TVA (%)')),
                ('low_stock_threshold_default', models.PositiveIntegerField(default=5, verbose_name='seuil de stock bas')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.compte')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.unit')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
            },
        ),
        migrations.CreateModel(
            name='ProductBoutiquePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_override', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('low_stock_threshold_override', models.PositiveIntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_overrides', to='tenants.boutique')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutique_overrides', to='catalog.product')),
            ],
            options={
                'verbose_name': 'prix boutique',
                'verbose_name_plural': 'prix boutique',
                'constraints': [models.UniqueConstraint(fields=('product', 'boutique'), name='unique_product_boutique_price')],
            },
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('compte', 'name'), name='unique_unit_name_par_compte'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('compte', 'sku'), name='unique_sku_par_compte'),
        ),
    ]
