# Generated by Django 6.0.7 on 2026-08-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='photo'),
        ),
    ]
