# Generated by Django 6.0.2 on 2026-09-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productboutiqueprice_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Laisser vide pour un produit sans date de péremption.', null=True, verbose_name='date de péremption'),
        ),
    ]
