# Generated by Django 6.0.2 on 2026-09-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name="prix d'achat"),
        ),
    ]
