# Generated by Django 6.0.2 on 2026-09-17 13:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
        ('sales', '0008_invoice_delivered_at_invoice_delivered_by_and_more'),
        ('tenants', '0010_boutique_delivery_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('CREDIT', 'Crédit'), ('DEBIT', 'Débit')], max_length=10)),
                ('kind', models.CharField(choices=[('TRANSFERT', 'Transfert entre collaborateurs'), ('LIVRAISON', 'Frais de livraison')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('transfer_id', models.UUIDField(blank=True, null=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.boutique')),
                ('commande', models.ForeignKey(blank=True, help_text="Commande à l'origine du débit, pour un mouvement de type « Frais de livraison ».", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.invoice')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_cash_movements_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_cash_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mouvement de caisse individuelle',
                'verbose_name_plural': 'mouvements de caisse individuelle',
                'ordering': ['-created_at'],
            },
        ),
    ]
