# Generated by Django 6.0.2 on 2026-09-17 14:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_personalcashmovement'),
        ('tenants', '0010_boutique_delivery_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.boutique')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transfers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transfert de caisse',
                'verbose_name_plural': 'transferts de caisse',
                'ordering': ['-created_at'],
            },
        ),
    ]
