# Generated by Django 6.0.2 on 2026-09-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_cashtransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcashmovement',
            name='kind',
            field=models.CharField(choices=[('TRANSFERT', 'Transfert entre collaborateurs'), ('LIVRAISON', 'Frais de livraison'), ('DEPENSE', 'Dépense')], max_length=20),
        ),
    ]
